trigger:
  branches:
    include:
    - main
  paths:
    include:
    - bicep/modules
    - bicep/module2.bicep
    - pipelines/pipeline-iac.yml

name: IaC Module

variables:
  - group: pipeline-variables

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy with Bicep
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: $(serviceConnectionName)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: './bicep/module2.bicep' 
    overrideParameters: '-prefix "$(prefix)" -sqlAdministratorLogin "$(sqlAdminUsername)" -sqlAdministratorLoginPassword "$(sqlAdminPassword)"'
    deploymentMode: 'Incremental'
    deploymentName: '$(prefix)'
